import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/* Import de componentes */
import NavBar from "@/components/elements/navbar";
import Footer from "@/components/elements/footer";
import { TooltipProvider } from "@/components/ui/tooltip";
import NextAuthProvider from "./providers/session-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rambell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <NextAuthProvider>
          <TooltipProvider>
            <NavBar />
            {children}
            <Footer />
          </TooltipProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
